"""
main.py — the wire. FastAPI server tying capture -> extract -> engine
together, per day-plan.md step 6.

    POST /assess
        body: {"audio_paths": [str, ...], "image_path": str|null,
               "actions_taken": [str], "language_code": str}
        -> the contract.json shape (differential, cant_miss, best_question,
           runners_up, misfits, ...) PLUS "transcript" and "_evidence", so
           the caller can see what capture.py heard and what extract.py
           derived from it, not just the final numbers. Also, best-effort,
           "question_audio_b64" (base64 WAV, bulbul-v3) plus
           "question_audio_for_id" and "question_audio_language". If
           language_code is "hi-IN" AND the computed question has a
           hand-written Hindi entry in HINDI_QUESTIONS below, that Hindi
           text is spoken. Otherwise — any other language, or Hindi with no
           matching entry — this FALLS BACK to speaking the raw English
           question_en in en-IN ("question_audio_fallback": true), rather
           than staying silent or erroring. All these fields are simply
           absent if TTS itself fails; TTS failure never fails the whole
           call. language_code also selects the STT language passed to
           capture.transcribe() for every audio_path; defaults to "hi-IN".

        audio_paths is a LIST because the demo's consultation is recorded as
        several short single-utterance files (demo/mock_hi-IN/mock_line_*.wav)
        rather than one long take — each is transcribed and the results are
        joined into one transcript for extract.py. A single-element list
        works fine for a one-file consultation too.

        Any failure in transcription, document scanning, or evidence
        extraction is caught and returned as a clean 502 JSON error
        ({"detail": "..."}) rather than an unhandled 500 — there's no
        offline fallback anymore, so a live failure mid-pitch needs to fail
        gracefully, not crash.

    GET /contract.json  -> serves contract.json from the repo root, so the
        EXISTING static frontend (web/index.html's fetch('../contract.json'))
        keeps working unchanged when served through this app instead of
        `python -m http.server`.

    GET /web/...  -> serves web/index.html and anything else under web/.

    --offline  -> every /assess call replays demo/offline_response.json
        instead of touching Sarvam/Anthropic at all. day-plan.md's explicit
        safety net for bad venue wifi. YOU MUST CREATE THAT FILE before this
        flag is usable — it isn't generated by this script. Easiest way:
        `python demo_case.py --dump --stage 2` to get a real engine payload
        into contract.json, copy it to demo/offline_response.json, and add
        a "transcript" key with whatever the real backup recording actually
        says (or the mock transcript, if that's what's being demoed).

NOTE: only the FastAPI/Starlette plumbing here is "obviously correct" —
capture.py and extract.py's own internals were each wrong on first attempt
and needed verification against the real SDKs. This file hasn't been run
yet (no network from where it was written). Before trusting it: run it,
POST a real request at /assess, and confirm the response shape actually
matches what web/index.html would need — don't assume the glue is right
just because each piece was individually verified.

Usage:
    pip install fastapi "uvicorn[standard]" pydantic
    python main.py                  # live, http://127.0.0.1:8000/web/
    python main.py --offline        # replay demo/offline_response.json
    python main.py --port 8080
"""
import argparse
import base64
import json
import sys
import tempfile
from pathlib import Path

from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse, RedirectResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel

import capture
import extract
from engine import Engine

REPO_ROOT = Path(__file__).parent
CONTRACT_PATH = REPO_ROOT / "contract.json"
OFFLINE_RESPONSE_PATH = REPO_ROOT / "demo" / "offline_response.json"

# engine.py's best_question only ever carries English (question_en from
# DDXPlus — there's no Hindi field anywhere in the dataset or in
# Engine.best_question()'s output, confirmed by reading engine.py directly,
# not assumed). Speaking a question aloud therefore needs a hand-written
# Hindi translation, and only for the ONE question this demo actually asks
# — web/index.html's FOLLOW_QUESTION_ID already pins the displayed/spoken
# question to E_151 for narrative consistency (day-plan.md's deliberate
# choice, see that file's comment), so that's the only code worth having a
# translation for here. UNVERIFIED hand-written Hindi, not checked by a
# native speaker — MUST match web/index.html's HINDI_Q[E_151] exactly,
# since that's the on-screen text for the same spoken line.
HINDI_QUESTIONS = {
    "E_151": "क्या आपके शरीर में कहीं सूजन है?",
}


def _pick_hindi_question(payload):
    """Mirrors web/index.html's pickQuestion(): prefer best_question if its
    id is one we have Hindi for, else look through runners_up. Returns
    (evidence_id, hindi_text) or (None, None) if no match — TTS is best
    effort, not every stage's computed question has a translation."""
    candidates = [payload.get("best_question")] + list(payload.get("runners_up") or [])
    for q in candidates:
        if q and q.get("id") in HINDI_QUESTIONS:
            return q["id"], HINDI_QUESTIONS[q["id"]]
    return None, None

app = FastAPI(title="AnviksaAI")

_engine = None
_offline = False  # set from --offline in __main__; read by the /assess route


def get_engine():
    global _engine
    if _engine is None:
        _engine = Engine.load()
    return _engine


class AssessRequest(BaseModel):
    audio_paths: list[str]
    image_path: str | None = None
    actions_taken: list[str] = []
    # BCP-47 code, restricted client-side to bulbul-v3's 11 TTS-supported
    # languages (see web/index.html's LANGUAGES) even though saaras-v3 STT
    # itself understands more — a language with no TTS voice couldn't ever
    # speak best_question aloud, so there's no point offering it here.
    language_code: str = "hi-IN"


@app.post("/assess")
def assess(req: AssessRequest):
    if _offline:
        if not OFFLINE_RESPONSE_PATH.exists():
            raise HTTPException(
                500,
                f"--offline is set but {OFFLINE_RESPONSE_PATH} doesn't exist "
                "yet — see this file's module docstring for how to create it.",
            )
        return json.loads(OFFLINE_RESPONSE_PATH.read_text(encoding="utf-8"))

    # capture.transcribe() returns the full batch-STT result dict (diarized
    # entries, request_id, etc.) — extract.py only needs the flat transcript
    # text, not per-speaker attribution, so that's all that's passed on.
    # See capture.py's transcribe() docstring for the full return shape if
    # diarization ever needs to reach extract.py too.
    transcript_parts = []
    for p in req.audio_paths:
        audio_path = Path(p)
        if not audio_path.exists():
            raise HTTPException(400, f"audio_path not found: {audio_path}")
        try:
            stt_result = capture.transcribe(str(audio_path), language_code=req.language_code)
        except Exception as e:
            raise HTTPException(502, f"transcription failed for {audio_path.name}: {e}")
        transcript_parts.append(stt_result["transcript"])
    transcript = "\n".join(transcript_parts)

    doc_text = ""
    if req.image_path:
        image_path = Path(req.image_path)
        if not image_path.exists():
            raise HTTPException(400, f"image_path not found: {image_path}")
        try:
            doc_text = capture.read_image(str(image_path))["text"]
        except Exception as e:
            raise HTTPException(502, f"document scan failed: {e}")

    try:
        evidence = extract.extract(transcript, doc_text)
    except Exception as e:
        raise HTTPException(502, f"evidence extraction failed: {e}")

    payload = get_engine().assess(evidence, actions_taken=req.actions_taken)
    payload["transcript"] = transcript
    payload["_evidence"] = evidence

    # Best-effort spoken audio for the computed question, base64'd straight
    # into the response rather than a separate static route (nothing else
    # needs to serve this file, and it avoids a second round trip). A TTS
    # failure (rate limit, network) shouldn't take down an otherwise-good
    # assessment, so this is deliberately non-fatal — omit the field rather
    # than 502 the whole call.
    qid, qtext_hi = (_pick_hindi_question(payload)
                     if req.language_code == "hi-IN" else (None, None))
    if qtext_hi:
        try:
            with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as tmp:
                tmp_path = Path(tmp.name)
            capture.speak(qtext_hi, tmp_path, language_code="hi-IN")
            payload["question_audio_b64"] = base64.b64encode(tmp_path.read_bytes()).decode("ascii")
            payload["question_audio_for_id"] = qid
            payload["question_audio_language"] = "hi-IN"
            tmp_path.unlink(missing_ok=True)
        except Exception:
            pass
    else:
        # KNOWN LIMITATION: HINDI_QUESTIONS above is the only hand-written
        # translation that exists tonight. Every other selected language —
        # and Hindi itself, if the computed question has no Hindi entry —
        # falls back to speaking the raw English question_en text in en-IN,
        # so "ask this aloud" always produces SOME audio instead of silently
        # doing nothing or throwing. It is NOT a translation into the
        # patient's actual language; only the hi-IN path above is real for
        # this demo. A real deploy needs real per-language translations here.
        q = payload.get("best_question")
        if q and q.get("en"):
            try:
                with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as tmp:
                    tmp_path = Path(tmp.name)
                capture.speak(q["en"], tmp_path, language_code="en-IN")
                payload["question_audio_b64"] = base64.b64encode(tmp_path.read_bytes()).decode("ascii")
                payload["question_audio_for_id"] = q["id"]
                payload["question_audio_language"] = "en-IN"
                payload["question_audio_fallback"] = True
                tmp_path.unlink(missing_ok=True)
            except Exception:
                pass

    return payload


@app.get("/contract.json")
def serve_contract():
    if not CONTRACT_PATH.exists():
        raise HTTPException(404, "contract.json doesn't exist yet — run demo_case.py --dump-all")
    return FileResponse(CONTRACT_PATH, media_type="application/json")


@app.get("/")
def root():
    return RedirectResponse("/web/")


# Mounted at /web (NOT at "/") deliberately — mounting the whole repo root
# would also serve .env, the ddxplus/ CSVs, and .git/ over HTTP. Only
# web/index.html and the one explicit /contract.json route above are
# actually exposed.
app.mount("/web", StaticFiles(directory=str(REPO_ROOT / "web"), html=True), name="web")

# Also safe to expose directly: demo/ only ever holds the mock consult
# audio, the synthetic blister-strip photo, and their JSON manifest — no
# secrets, unlike the repo root. Lets web/index.html's per-line play
# buttons fetch the real recorded wav files straight from the browser
# instead of round-tripping them through /assess as base64.
app.mount("/demo", StaticFiles(directory=str(REPO_ROOT / "demo")), name="demo")


if __name__ == "__main__":
    if sys.platform == "win32":
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")

    ap = argparse.ArgumentParser()
    ap.add_argument("--offline", action="store_true",
                     help="replay demo/offline_response.json, no API calls at all")
    ap.add_argument("--port", type=int, default=8000)
    args = ap.parse_args()
    _offline = args.offline

    if _offline and not OFFLINE_RESPONSE_PATH.exists():
        print(f"WARNING: --offline set but {OFFLINE_RESPONSE_PATH} doesn't "
              f"exist yet. /assess will 500 until it's created — see this "
              f"file's module docstring.")

    import uvicorn
    print(f"Serving on http://127.0.0.1:{args.port}/web/  "
          f"({'OFFLINE — no API calls' if _offline else 'LIVE'})")
    uvicorn.run(app, host="127.0.0.1", port=args.port)
